apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sudoku

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: frontend

images:
  - name: YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/sudoku-backend
    newTag: stable
  - name: YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/sudoku-frontend
    newTag: stable
